// 100 romantic sentences for the Love Letter game
// Each sentence has good word variety for fill-in-the-blank questions

export const letterNotes: string[] = [
  "Seninle her gün yeni bir macera başlıyor",
  "Kalbimde senin için ayrılan yer hep sıcak",
  "Birlikte yürürken zaman duruyor sanki",
  "Gözlerinde kaybolmak istiyorum her gün",
  "Aşkımızın rengi her gün daha parlak",
  "Seninle konuşmak en güzel alışkanlığım",
  "Elini tuttuğumda dünya yerini buluyor",
  "Gülüşünde saklı bir bahar var",
  "Birlikteyken her şey biraz daha anlamlı",
  "Kalbim, adını her atışında fısıldıyor",
  "Seninle her an küçük bir mucize",
  "Düşlerimin en güzeli gerçeğim oldun",
  "Bugün de sevgini cebime koyup çıkıyorum",
  "Sessiz bir teşekkür varlığına",
  "Yollar uzasa da kalpler yakın",
  "Aşk senin adınla başlıyor bende",
  "Seninle olmak eve dönmek gibi",
  "Gözlerinde kaybolmayı bugün de deneyeceğim",
  "Senden sonra her şeyin tadı değişti",
  "Bir tebessümün tüm yorgunluğumu alıyor",
  "Aşkımız her gün yeniden doğuyor",
  "Bugün sana yeniden aşık oldum",
  "Kalbinin yanında dünya güvenli",
  "Seninle her gün küçük bir kutlama",
  "Sevdiğim en güzel alışkanlık sensin",
  "Bir bakışın bin şiir",
  "Bugün de sevgine sığındım",
  "Sessiz anlarımızın bile bir melodisi var",
  "Senle yürürken yol kısalıyor",
  "Aşkımızın gölgesinde serinliyorum",
  "Birlikteyken dünya biraz daha iyi",
  "Kelimeler yetmiyor kalbim anlatıyor",
  "Seninle her gün yeni bir hikaye",
  "Bir gülüşünle dünya güzelleşiyor",
  "Kalbim kalbinin ritmine alıştı çoktan",
  "Aşkımızın rengi bugün biraz daha parlak",
  "İyi ki varsın iyi ki biz varız",
  "Yanındayken zaman yavaşlıyor dünya sessizleşiyor",
  "Gözlerinin içinde kaybolmak istiyorum bugün de",
  "Bir dokunuşun bin huzur",
  "Senle her an küçük bir mucize",
  "Düşlerimin en güzeli gerçeğim oldun",
  "Kalbimde sana ayrılan yer hep en sıcak",
  "Bugün de sevgini cebime koyup çıkıyorum",
  "Sessiz bir teşekkür varlığına",
  "Yollar uzasa da kalpler yakın",
  "Aşk senin adınla başlıyor bende",
  "Birlikteyken her şey biraz daha anlamlı",
  "Gülüşünde saklı bir bahar var",
  "Seninle konuşmadan da anlaşmayı seviyorum",
  "Elini tuttuğumda dünya yerini buluyor",
  "Bugün dününden güzel çünkü sen varsın",
  "Aynı gökyüzüne bakıyoruz aynı rüyaları görüyoruz",
  "İki kalp tek ritim",
  "Seninle her gün küçük bir kutlama",
  "Sevdiğim en güzel alışkanlık sensin",
  "Kalbim adını her atışında fısıldıyor",
  "Bir bakışın bin şiir",
  "Bugün de sevgine sığındım",
  "Sessiz anlarımızın bile bir melodisi var",
  "Senle yürürken yol kısalıyor",
  "Aşkımızın gölgesinde serinliyorum",
  "Birlikteyken dünya biraz daha iyi",
  "Kelimeler yetmiyor kalbim anlatıyor",
  "Seninle olmak eve dönmek gibi",
  "Gözlerinde kaybolmayı bugün de deneyeceğim",
  "Senden sonra her şeyin tadı değişti",
  "Bir tebessümün tüm yorgunluğumu alıyor",
  "Aşkımız her gün yeniden doğuyor",
  "Bugün sana yeniden aşık oldum",
  "Kalbinin yanında dünya güvenli",
  "Seninle her gün yeni bir macera başlıyor",
  "Kalbimde senin için ayrılan yer hep sıcak",
  "Birlikte yürürken zaman duruyor sanki",
  "Gözlerinde kaybolmak istiyorum her gün",
  "Aşkımızın rengi her gün daha parlak",
  "Seninle konuşmak en güzel alışkanlığım",
  "Elini tuttuğumda dünya yerini buluyor",
  "Gülüşünde saklı bir bahar var",
  "Birlikteyken her şey biraz daha anlamlı",
  "Kalbim adını her atışında fısıldıyor",
  "Seninle her an küçük bir mucize",
  "Düşlerimin en güzeli gerçeğim oldun",
  "Bugün de sevgini cebime koyup çıkıyorum",
  "Sessiz bir teşekkür varlığına",
  "Yollar uzasa da kalpler yakın",
  "Aşk senin adınla başlıyor bende",
  "Seninle olmak eve dönmek gibi",
  "Gözlerinde kaybolmayı bugün de deneyeceğim",
  "Senden sonra her şeyin tadı değişti",
  "Bir tebessümün tüm yorgunluğumu alıyor",
  "Aşkımız her gün yeniden doğuyor",
  "Bugün sana yeniden aşık oldum",
  "Kalbinin yanında dünya güvenli",
  "Seninle her gün küçük bir kutlama",
  "Sevdiğim en güzel alışkanlık sensin",
  "Bir bakışın bin şiir",
  "Bugün de sevgine sığındım",
  "Sessiz anlarımızın bile bir melodisi var",
  "Senle yürürken yol kısalıyor",
  "Aşkımızın gölgesinde serinliyorum",
  "Birlikteyken dünya biraz daha iyi",
  "Kelimeler yetmiyor kalbim anlatıyor",
  "Seninle her gün yeni bir hikaye",
  "Bir gülüşünle dünya güzelleşiyor",
  "Kalbim kalbinin ritmine alıştı çoktan",
  "Aşkımızın rengi bugün biraz daha parlak",
  "İyi ki varsın iyi ki biz varız",
  "Yanındayken zaman yavaşlıyor dünya sessizleşiyor",
  "Gözlerinin içinde kaybolmak istiyorum bugün de",
  "Bir dokunuşun bin huzur",
  "Senle her an küçük bir mucize",
  "Düşlerimin en güzeli gerçeğim oldun",
  "Kalbimde sana ayrılan yer hep en sıcak",
  "Bugün de sevgini cebime koyup çıkıyorum",
  "Sessiz bir teşekkür varlığına",
  "Yollar uzasa da kalpler yakın",
  "Aşk senin adınla başlıyor bende",
  "Birlikteyken her şey biraz daha anlamlı",
  "Gülüşünde saklı bir bahar var",
  "Seninle konuşmadan da anlaşmayı seviyorum",
  "Elini tuttuğumda dünya yerini buluyor",
  "Bugün dününden güzel çünkü sen varsın",
  "Aynı gökyüzüne bakıyoruz aynı rüyaları görüyoruz",
  "İki kalp tek ritim"
];
